apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "radarr.fullname" . }}-media
  labels:
    type: local
spec:
  storageClassName: {{ .Values.persistence.media.storageClassName }}
  capacity:
    storage: {{ .Values.persistence.media.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ .Values.persistence.media.reclaimPolicy }}
  hostPath:
    path: {{ .Values.persistence.media.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "radarr.fullname" . }}-media-claim
spec:
  storageClassName: {{ .Values.persistence.media.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.media.size }}