apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "sonarr.fullname" . }}-media
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/Volumes/DATA/Media"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "sonarr.fullname" . }}-media-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi