apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "nzbget.fullname" . }}-config
  labels:
    type: local
spec:
  storageClassName: {{ .Values.persistence.config.storageClassName }}
  capacity:
    storage: {{ .Values.persistence.config.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ .Values.persistence.config.reclaimPolicy }}
  hostPath:
    path: {{ .Values.persistence.config.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "nzbget.fullname" . }}-config-claim
spec:
  storageClassName: {{ .Values.persistence.config.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}