apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nzbget.fullname" . }}
  labels:
    {{- include "nzbget.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  strategy:
    type: {{ .Values.deploymentStrategy }}
  selector:
    matchLabels:
      {{- include "nzbget.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nzbget.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PUID
              value: {{ .Values.environment.puid | quote }}
            - name: PGID
              value: {{ .Values.environment.pgid | quote }}
            - name: TZ
              value: {{ .Values.environment.timeZone | quote }}
          ports:
            - name: http
              containerPort: 6789
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
              httpHeaders:
                - name: Authorization
                  value: Basic bnpiZ2V0OnRlZ2J6bjY3ODk=
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /
              port: http
              httpHeaders:
                - name: Authorization
                  value: Basic bnpiZ2V0OnRlZ2J6bjY3ODk=
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /media/Downloads
              name: downloads
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ template "nzbget.fullname" . }}-config-claim
        - name: downloads
          persistentVolumeClaim:
            claimName: {{ template "nzbget.fullname" . }}-downloads-claim 