apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "nzbget.fullname" . }}-downloads
  labels:
    type: local
spec:
  storageClassName: {{ .Values.persistence.downloads.storageClassName }}
  capacity:
    storage: {{ .Values.persistence.downloads.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ .Values.persistence.downloads.reclaimPolicy }}
  hostPath:
    path: {{ .Values.persistence.downloads.hostPath }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "nzbget.fullname" . }}-downloads-claim
spec:
  storageClassName: {{ .Values.persistence.downloads.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.downloads.size }}