replicaCount: 1
image:
  repository: quay.io/influxdb/telegraf-operator
  pullPolicy: IfNotPresent
  sidecarImage: "docker.io/library/telegraf:1.14.4"

classes:
  secretName: "telegraf-operator-classes"
  default: "app"
  data:
    app: |
      [[outputs.influxdb_v2]]
        urls = ["http://influxdb2"]
        token = "tNjkwZHcsjZbwc2H6zvCMJ6jBGHy5hCFmXvv5JZdYHj6TJtnJFs2XDcG"
        organization = "leonmachado.homelab"
        bucket = "application-metrics"
        timeout = "5s"
      [global_tags]
        hostname = "$HOSTNAME"
        nodename = "$NODENAME"
        type = "app"
    infra: |
      [[outputs.influxdb_v2]]
        urls = ["http://influxdb2"]
        token = "tNjkwZHcsjZbwc2H6zvCMJ6jBGHy5hCFmXvv5JZdYHj6TJtnJFs2XDcG"
        organization = "leonmachado.homelab"
        bucket = "infrastructure-metrics"
        timeout = "5s"
      [global_tags]
        hostname = "$HOSTNAME"
        nodename = "$NODENAME"
        type = "infra"

certManager:
  enable: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  # Annotations to add to the service account
  annotations: {}
podSecurityContext: {}
  # fsGroup: 2000
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi
nodeSelector: {}
tolerations: []
affinity: {}
requireAnnotationsForSecret: false
