apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "job-search-workflow.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "job-search-workflow.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.config | nindent 4 }}
  criteria.md: |
    {{- .Values.criteria | nindent 4 }}
