# Default values for sonarr.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: linuxserver/radarr
  tag: latest
  pullPolicy: IfNotPresent

deploymentStrategy: Recreate

probes:
  liveness:
    initialDelaySeconds: 60
    failureThreshold: 6
    timeoutSeconds: 1
  readiness:
    initialDelaySeconds: 20
    failureThreshold: 3
    timeoutSeconds: 1

nameOverride: ""
fullnameOverride: ""

environment:
  puid: 1000
  pgid: 1000
  timeZonw: America/New York

service:
  type: ClusterIP
  port: 80

ingress:    
  host: radarr.littlelodge.local
  path: /

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi
