apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "sonarr.fullname" . }}-config
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/lib/.sonarr"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "sonarr.fullname" . }}-config-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi