# Default values for nzbget.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

deploymentStrategy: Recreate

image:
  repository: linuxserver/nzbget
  tag: version-v21.1
  pullPolicy: Always

probes:
  liveness:
    initialDelaySeconds: 60
    failureThreshold: 6
    timeoutSeconds: 1
  readiness:
    initialDelaySeconds: 20
    failureThreshold: 3
    timeoutSeconds: 1

environment:
  puid: 1000
  pgid: 1000
  timeZone: America/New York

service:
  type: ClusterIP
  port: 80

ingress:
  ingressClassName: # nginx
  host: nzbget.leonmachado.com
  path: /
