apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "mariadb.fullname" . }}-data-claim
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi