# Default values for nzbget.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

deploymentStrategy: Recreate

image:
  repository: linuxserver/mariadb
  tag: latest
  pullPolicy: IfNotPresent

probes:
  liveness:
    initialDelaySeconds: 60
    failureThreshold: 6
    timeoutSeconds: 1
  readiness:
    initialDelaySeconds: 20
    failureThreshold: 3
    timeoutSeconds: 1

environment:
  puid: 1000
  pgid: 1000
  rootPassword: rootPassword
  timeZone: America/New York

service:
  type: ClusterIP
  port: 3306

ingress:    
  host: mysql.le.local
  path: /

  resources:
    limits:
      cpu: 1000m
      memory: 640Mi
    requests:
      cpu: 100m
      memory: 256Mi
