# Default values for nzbget.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

deploymentStrategy: Recreate

annotations:
  telegraf.influxdata.com/class: infra
  telegraf.influxdata.com/inputs:  |
    [[inputs.mysql]]
      servers = ["tcp://127.0.0.0:3306/"]
      metric_version = 2
      gather_process_list = true

image:
  repository: linuxserver/mariadb
  tag: latest
  pullPolicy: IfNotPresent

probes:
  liveness:
    initialDelaySeconds: 60
    failureThreshold: 6
    timeoutSeconds: 1
  readiness:
    initialDelaySeconds: 20
    failureThreshold: 3
    timeoutSeconds: 1

environment:
  puid: 1000
  pgid: 1000
  rootPassword: somePassw0rd*
  timeZone: America/New York

service:
  type: ClusterIP
  port: 3306

ingress:    
  host: mysql.lonmachado.com
  path: /

  resources:
    limits:
      cpu: 1000m
      memory: 640Mi
    requests:
      cpu: 100m
      memory: 256Mi
