replicaCount: 1

image:
  repository: linuxserver/radarr
  tag: latest
  pullPolicy: Always

deploymentStrategy: Recreate

probes:
  liveness:
    initialDelaySeconds: 60
    failureThreshold: 6
    timeoutSeconds: 1
  readiness:
    initialDelaySeconds: 20
    failureThreshold: 3
    timeoutSeconds: 1

environment:
  puid: 1000
  pgid: 1000
  timeZone: America/New York

service:
  type: ClusterIP
  port: 80

ingress:
  ingressClassName: # nginx
  pathType: Prefix
  host: radarr.local
  path: /

persistence:
  config:
    storageClassName: manual
    hostPath: /var/lib/.radarr
    mountPath: /config
    reclaimPolicy: Retain
    size: 1Mi

  media:
    storageClassName: manual
    hostPath: /var/lib/media
    mountPath: /media
    reclaimPolicy: Retain
    size: 50Gi
