apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "mariadb.fullname" . }}-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/lib/mariadb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "mariadb.fullname" . }}-data-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi