{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "octopus-deploy.serviceAccountName" . }}
  labels:
{{ include "octopus-deploy.labels" . | nindent 4 }}
{{- end -}}
